# Configuration for MNIST Classification

run_id: mnist_${now:%Y%m%d_%H%M%S}
seed: 42

data:
  batch_size: 64
  val_split: 0.1
  num_workers: 4

model:
  hidden_dim: 128
  dropout: 0.5

training:
  epochs: 10
  lr: 0.001
  weight_decay: 0.0001
  early_stop_patience: 5

checkpoint:
  keep_last: 3
  keep_best: 5

tracking:
  wandb: false
  tensorboard: false
  project: mnist-experiments
